---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-gengqianyu-io-v1beta1-gengdaemonset
  failurePolicy: Fail
  name: mgengdaemonset.kb.io
  rules:
  - apiGroups:
    - apps.gengqianyu.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gengdaemonsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-gengqianyu-io-v1beta1-gengdaemonset
  failurePolicy: Fail
  name: vgengdaemonset.kb.io
  rules:
  - apiGroups:
    - apps.gengqianyu.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gengdaemonsets
  sideEffects: None
