# permissions for end users to view gengdaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gengdaemonset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: daemon-operator
    app.kubernetes.io/part-of: daemon-operator
    app.kubernetes.io/managed-by: kustomize
  name: gengdaemonset-viewer-role
rules:
- apiGroups:
  - apps.gengqianyu.io
  resources:
  - gengdaemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.gengqianyu.io
  resources:
  - gengdaemonsets/status
  verbs:
  - get
