# permissions for end users to edit gengdaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gengdaemonset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: daemon-operator
    app.kubernetes.io/part-of: daemon-operator
    app.kubernetes.io/managed-by: kustomize
  name: gengdaemonset-editor-role
rules:
- apiGroups:
  - apps.gengqianyu.io
  resources:
  - gengdaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gengqianyu.io
  resources:
  - gengdaemonsets/status
  verbs:
  - get
