resources:
# 所有 RBAC 都将应用于 deployment 声明的命名空间中的此服务帐户下。
# 如果您的 manager 将使用运行时存在的服务帐户，则可以注释掉此资源。
# 如果更改服务帐户名称，请务必更新 RoleBinding 和 ClusterRoleBinding 主题。
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# 如果您想禁用保护 /metrics 端点的 auth 代理 （https://github.com/brancz/kube-rbac-proxy），请注释以下 4 行。
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
